import "./App.css";
import React from "react";
import Dictionary from "./Dictionary";
// import KassLogo from "./KassLogo.jpg";

export default function App() {
  let defaultTerm = "frosting";
  let randomClicked = true;
  // let arrayOfTerms = [
  //   "bemused",
  //   "butter",
  //   "banal",
  //   "contrive",
  //   "colloquial",
  //   "deferential",
  //   "existential",
  //   "facetious",
  //   "fortuitous",
  //   "incongruous",
  //   "inflammable",
  //   "deliniation",
  //   "contempt",
  //   "contentious",
  //   "armistice",
  //   "posthumous",
  //   "hubris",
  //   "cavalier",
  //   "postulate",
  //   "posterior",
  //   "infamous",
  //   "modicum",
  //   "moot",
  //   "myriad",
  //   "sun",
  //   "moon",
  //   "stars",
  //   "sparkles",
  //   "color",
  //   "beach",
  //   "ocean",
  //   "butter",
  //   "bread",
  //   "glass",
  //   "pistachio",
  //   "lavender",
  //   "nuance",
  //   "paradox",
  //   "penchant",
  //   "perfunctory",
  //   "peruse",
  //   "plethora",
  //   "deliniate",
  //   "extrapolate",
  //   "dysania",
  //   "serendipity",
  //   "quixotic",
  //   "caruncle",
  //   "osculator",
  //   "limerance",
  //   "atrate",
  //   "metanoia",
  //   "pauciloquent",
  //   "cacoethes",
  //   "vaticinate",
  //   "zoilism",
  //   "mephitic",
  //   "febrile",
  //   "tittle",
  //   "idoneous",
  //   "kenspeckle",
  //   "equivocate",
  //   "tergiversate",
  //   "gigle",
  //   "malarkey",
  //   "bravado",
  //   "darkle",
  //   "interfenestration",
  //   "scintillate",
  //   "sparsile",
  //   "tittynope",
  //   "absquatulate",
  //   "blatherskite",
  //   "microcosm",
  //   "pedantic",
  //   "belie",
  //   "axiom",
  //   "ascertain",
  //   "idempotent",
  //   "premise",
  //   "conjecture",
  //   "paradigm",
  //   "teem",
  //   "inductive",
  //   "incredulous",
  //   "laudable",
  //   "postulate",
  //   "supposition",
  //   "transient",
  //   "transitory",
  //   "epistimology",
  //   "acquiesce",
  //   "alacrity",
  //   "arcane",
  //   "Quintessential",
  //   "Umbrage",
  //   "Exorbitant",
  //   "amiable",
  //   "Seldom",
  //   "Accolade",
  //   "Catch-22",
  //   "Cloying",
  //   "Toilsome",
  //   "Cajole",
  //   "Ubiquitous",
  //   "quiet",
  //   "Boondoggle",
  //   "Perfunctory",
  //   "Eclectic",
  //   "Sycophant",
  //   "Proclivity",
  //   "Dalliance",
  //   "Insidious",
  //   "Euphemism",
  //   "innate",
  //   "inherent",
  //   "facetious",
  //   "Fastidious",
  //   "Cacophony",
  //   "Flummoxed",
  //   "nonsequitur",
  //   "Vitriol",
  //   "Flabbergasted",
  //   "Litany",
  //   "Narcissist",
  //   "Oblivion",
  //   "Ostentatious",
  //   "boat",
  //   "sun",
  //   "water",
  //   "fish",
  //   "yoga",
  //   "book",
  //   "toys",
  //   "phones",
  //   "horses",
  //   "horse",
  //   "kittens",
  //   "puppies",
  //   "love",
  //   "coffee",
  //   "plants",
  //   "candy",
  //   "frosting",
  //   "shopping",
  //   "fashion",
  //   "computers",
  //   "houses",
  //   "frogs",
  //   "quotes",
  //   "goats",
  //   "dogs",
  //   "cats",
  //   "elephants",
  //   "lizzards",
  //   "hands",
  //   "puzzle",
  //   "gorilla",
  //   "potatoes",
  //   "fruit",
  //   "ice cream",
  //   "berries",
  //   "produce",
  //   "friends",
  //   "party",
  //   "community",
  //   "kids",
  //   "cars",
  //   "gardening",
  //   "beach",
  //   "mountains",
  //   "home",
  //   "travel",
  //   "destination",
  //   "cup",
  //   "boat",
  //   "sun",
  //   "water",
  //   "fish",
  //   "yoga",
  //   "book",
  //   "toys",
  //   "phones",
  //   "horses",
  //   "horse",
  //   "kittens",
  //   "puppies",
  //   "love",
  //   "coffee",
  //   "plants",
  //   "candy",
  //   "shopping",
  //   "fashion",
  //   "computers",
  //   "houses",
  //   "frogs",
  //   "quotes",
  //   "goats",
  //   "dogs",
  //   "cats",
  //   "elephants",
  //   "lizzards",
  //   "hands",
  //   "puzzle",
  //   "gorilla",
  //   "sunrise",
  //   "fruit",
  //   "ice cream",
  //   "berries",
  //   "produce",
  //   "friends",
  //   "chocolate",
  //   "caramel",
  //   "ribbons",
  //   "butterfly",
  //   "art",
  //   "party",
  //   "community",
  //   "kids",
  //   "cars",
  //   "gardening",
  //   "beach",
  //   "mountains",
  //   "home",
  //   "travel",
  //   "Tryst",
  //   "Caustic",
  //   "Coerce",
  //   "candy",
  //   "dolls",
  //   "food",
  //   "drinks",
  //   "bar",
  //   "beauty",
  //   "baby",
  //   "ducks",
  //   "beer",
  //   "cake",
  //   "cupcake",
  //   "french",
  //   "kindness",
  //   "ingenious",
  //   "superior",
  //   "subsequently",
  //   "unequivocally",
  //   "plethora",
  //   "Epitome",
  //   "immense",
  //   "exquisite",
  //   "diminutive",
  //   "benevolent",
  //   "despicable",
  //   "fundamentally",
  //   "essential",
  //   "examine",
  //   "Acrimony",
  //   "Adept",
  //   "Adulation",
  //   "Ambivalent",
  //   "Anomaly",
  //   "boat",
  //   "water",
  //   "book",
  //   "kittens",
  //   "candy",
  //   "maybe",
  //   "no",
  //   "yes",
  //   "houses",
  //   "frogs",
  //   "fries",
  //   "goats",
  //   "dogs",
  //   "cats",
  //   "elephants",
  //   "lizzards",
  //   "lollipop",
  //   "berries",
  //   "sunset",
  //   "friends",
  //   "party",
  //   "sunrise",
  //   "candy",
  //   "search",
  //   "gardening",
  //   "beach",
  //   "mountains",
  //   "cup",
  //   "Avant-garde",
  //   "Axiomatic",
  //   "Acquiesce",
  //   "Nefarious",
  //   "comport",
  //   "contrition",
  //   "abhor",
  //   "subsequent",
  //   "stars",
  //   "country",
  //   "concurrency",
  //   "anomoloaus",
  //   "inumerate",
  //   "autonymous",
  //   "defacto",
  //   "overzealous",
  //   "impervious",
  //   "donut",
  //   "nihilism",
  //   "spirtual",
  //   "certitude",
  //   "flippant",
  //   "sparkle",
  //   "color",
  //   "ant",
  //   "love",
  //   "coffee",
  //   "plants",
  //   "candy",
  //   "gorilla",
  //   "cow",
  //   "fruit",
  //   "ice cream",
  //   "berries",
  //   "peace",
  //   "oneness",
  //   "community",
  //   "skittles",
  //   "sprinkles",
  //   "watermelon",
  //   "cup",
  //   "diffidence",
  //   "disputation",
  //   "abberation",
  //   "veridical",
  //   "pursuant",
  //   "awakening",
  //   "anecdotal",
  // ];
  // const date = new Date();
  // let ms = date.getMilliseconds() % 100;
  // let defaultTerm = arrayOfTerms[ms];

  function handleRandomWord(event) {
    event.preventDefault();
    randomClicked = true;
    console.log(
      ` in handleRandomWord function in App.js ${event} and defaultTerm is ${defaultTerm}`
    );

    let arrayOfTerms = [
      "bemused",
      "butter",
      "banal",
      "contrive",
      "colloquial",
      "deferential",
      "existential",
      "facetious",
      "fortuitous",
      "incongruous",
      "inflammable",
      "deliniation",
      "contempt",
      "contentious",
      "armistice",
      "posthumous",
      "hubris",
      "cavalier",
      "postulate",
      "posterior",
      "infamous",
      "modicum",
      "moot",
      "myriad",
      "sun",
      "moon",
      "stars",
      "sparkles",
      "color",
      "beach",
      "ocean",
      "butter",
      "bread",
      "glass",
      "pistachio",
      "lavender",
      "nuance",
      "paradox",
      "penchant",
      "perfunctory",
      "peruse",
      "plethora",
      "deliniate",
      "extrapolate",
      "dysania",
      "serendipity",
      "quixotic",
      "caruncle",
      "osculator",
      "limerance",
      "atrate",
      "metanoia",
      "pauciloquent",
      "cacoethes",
      "vaticinate",
      "zoilism",
      "mephitic",
      "febrile",
      "tittle",
      "idoneous",
      "kenspeckle",
      "equivocate",
      "tergiversate",
      "gigle",
      "malarkey",
      "bravado",
      "darkle",
      "interfenestration",
      "scintillate",
      "sparsile",
      "tittynope",
      "absquatulate",
      "blatherskite",
      "microcosm",
      "pedantic",
      "belie",
      "axiom",
      "ascertain",
      "idempotent",
      "premise",
      "conjecture",
      "paradigm",
      "teem",
      "inductive",
      "incredulous",
      "laudable",
      "postulate",
      "supposition",
      "transient",
      "transitory",
      "epistimology",
      "acquiesce",
      "alacrity",
      "arcane",
      "Quintessential",
      "Umbrage",
      "Exorbitant",
      "amiable",
      "Seldom",
      "Accolade",
      "Catch-22",
      "Cloying",
      "Toilsome",
      "Cajole",
      "Ubiquitous",
      "quiet",
      "Boondoggle",
      "Perfunctory",
      "Eclectic",
      "Sycophant",
      "Proclivity",
      "Dalliance",
      "Insidious",
      "Euphemism",
      "innate",
      "inherent",
      "facetious",
      "Fastidious",
      "Cacophony",
      "Flummoxed",
      "nonsequitur",
      "Vitriol",
      "Flabbergasted",
      "Litany",
      "Narcissist",
      "Oblivion",
      "Ostentatious",
      "boat",
      "sun",
      "water",
      "fish",
      "yoga",
      "book",
      "toys",
      "phones",
      "horses",
      "horse",
      "kittens",
      "puppies",
      "love",
      "coffee",
      "plants",
      "candy",
      "frosting",
      "shopping",
      "fashion",
      "computers",
      "houses",
      "frogs",
      "quotes",
      "goats",
      "dogs",
      "cats",
      "elephants",
      "lizzards",
      "hands",
      "puzzle",
      "gorilla",
      "potatoes",
      "fruit",
      "ice cream",
      "berries",
      "produce",
      "friends",
      "party",
      "community",
      "kids",
      "cars",
      "gardening",
      "beach",
      "mountains",
      "home",
      "travel",
      "destination",
      "cup",
      "boat",
      "sun",
      "water",
      "fish",
      "yoga",
      "book",
      "toys",
      "phones",
      "horses",
      "horse",
      "kittens",
      "puppies",
      "love",
      "coffee",
      "plants",
      "candy",
      "shopping",
      "fashion",
      "computers",
      "houses",
      "frogs",
      "quotes",
      "goats",
      "dogs",
      "cats",
      "elephants",
      "lizzards",
      "hands",
      "puzzle",
      "gorilla",
      "sunrise",
      "fruit",
      "ice cream",
      "berries",
      "produce",
      "friends",
      "chocolate",
      "caramel",
      "ribbons",
      "butterfly",
      "art",
      "party",
      "community",
      "kids",
      "cars",
      "gardening",
      "beach",
      "mountains",
      "home",
      "travel",
      "Tryst",
      "Caustic",
      "Coerce",
      "candy",
      "dolls",
      "food",
      "drinks",
      "bar",
      "beauty",
      "baby",
      "ducks",
      "beer",
      "cake",
      "cupcake",
      "french",
      "kindness",
      "ingenious",
      "superior",
      "subsequently",
      "unequivocally",
      "plethora",
      "Epitome",
      "immense",
      "exquisite",
      "diminutive",
      "benevolent",
      "despicable",
      "fundamentally",
      "essential",
      "examine",
      "Acrimony",
      "Adept",
      "Adulation",
      "Ambivalent",
      "Anomaly",
      "boat",
      "water",
      "book",
      "kittens",
      "candy",
      "maybe",
      "no",
      "yes",
      "houses",
      "frogs",
      "fries",
      "goats",
      "dogs",
      "cats",
      "elephants",
      "lizzards",
      "lollipop",
      "berries",
      "sunset",
      "friends",
      "party",
      "sunrise",
      "candy",
      "search",
      "gardening",
      "beach",
      "mountains",
      "cup",
      "Avant-garde",
      "Axiomatic",
      "Acquiesce",
      "Nefarious",
      "comport",
      "contrition",
      "abhor",
      "subsequent",
      "stars",
      "country",
      "concurrency",
      "anomoloaus",
      "inumerate",
      "autonymous",
      "defacto",
      "overzealous",
      "impervious",
      "donut",
      "nihilism",
      "spirtual",
      "certitude",
      "flippant",
      "sparkle",
      "color",
      "ant",
      "love",
      "coffee",
      "plants",
      "candy",
      "gorilla",
      "cow",
      "fruit",
      "ice cream",
      "berries",
      "peace",
      "oneness",
      "community",
      "skittles",
      "sprinkles",
      "watermelon",
      "cup",
      "diffidence",
      "disputation",
      "abberation",
      "veridical",
      "pursuant",
      "awakening",
      "anecdotal",
    ];

    const date = new Date();
    let ms = date.getMilliseconds() % 100;
    defaultTerm = arrayOfTerms[ms];
    console.log(
      `&&&&& IN APP.JS FILE @@@@  defaultTerm is ${defaultTerm} and randomClicked is ${randomClicked}`
    );
  }

  if (defaultTerm != null) {
    return (
      <div className="App">
        <div className="container">
          {/* <img src="./KassLogo.jpg" className="AppLogo" alt="logo" /> */}
          <h1 className="dictionaryHeader">
            Dictionary App{" "}
            <a
              href="https://www.freeiconspng.com/img/25701"
              title="Image from freeiconspng.com"
            >
              <img
                src="https://www.freeiconspng.com/uploads/blue-book-png-31.png"
                width="75"
                alt="blue book png"
              />
            </a>
          </h1>
          <button className="randomWord" onClick={handleRandomWord}>
            Random Word
          </button>
          {/* <Dictionary defaultTerm={defaultTerm} />  */}

          <Dictionary defaultTerm={defaultTerm} />
          <p></p>
          <footer className="dictionaryFooter">
            {" "}
            This project is coded by{" "}
            <a
              href="https://kassiewhite.netlify.app/index.html"
              target="_blank"
              rel="noreferrer"
            >
              Kassie White
            </a>{" "}
            and it is{" "}
            <a
              href="https://github.com/whitekf/react-dictionary-app"
              target="_blank"
              rel="noreferrer"
            >
              Open-Sourced
            </a>
          </footer>
        </div>
      </div>
    );
  } else return null;
}
